"""empty message

Revision ID: 25662369851c
Revises: 9d2ee3c85fc1
Create Date: 2021-03-31 20:40:17.194089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25662369851c'
down_revision = '9d2ee3c85fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('imdb_poster_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'imdb_poster_uri')
    # ### end Alembic commands ###
