"""add Release.deleted

Revision ID: 2e51bce72577
Revises: 78c8669529c7
Create Date: 2021-04-03 18:51:21.927459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e51bce72577'
down_revision = '78c8669529c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'delete')
    # ### end Alembic commands ###
