"""add Release.source

Revision ID: 78c8669529c7
Revises: 47cd43ad1031
Create Date: 2021-04-03 09:05:08.088037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c8669529c7'
down_revision = '47cd43ad1031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'source')
    # ### end Alembic commands ###
