"""empty message

Revision ID: 8f14acc8a818
Revises: 525065b36c20
Create Date: 2021-03-24 15:03:46.359065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f14acc8a818'
down_revision = '525065b36c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show_country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('country_id', 'show_id')
    )
    op.add_column('show', sa.Column('user_rating', sa.Integer(), nullable=True))
    op.add_column('show', sa.Column('user_view_date', sa.DateTime(), nullable=True))
    op.add_column('show', sa.Column('validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'validated')
    op.drop_column('show', 'user_view_date')
    op.drop_column('show', 'user_rating')
    op.drop_table('show_country')
    op.drop_table('country')
    # ### end Alembic commands ###
