"""add Show.user_viewed

Revision ID: d2b16ed22dae
Revises: f28cd22135c5
Create Date: 2021-04-02 13:37:37.742220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b16ed22dae'
down_revision = 'f28cd22135c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('user_viewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'user_viewed')
    # ### end Alembic commands ###
